<?php

class CustomHashServiceProvider extends Illuminate\Support\ServiceProvider{
    public function register()
    {
        // TODO: Implement register() method.
        $this->app->bind('hash', function(){
           return new CustomHasher();
        });
    }

    public function provides()
    {
        return array('hash'); // TODO: Change the autogenerated stub
    }
}